---
# Enable Ansible Repository on RHEL7:
- name: Enable Ansible Repo - RHEL7
  community.general.rhsm_repository:
    name  : rhel-7-server-ansible-2.9-rpms
    state : enabled
  when:
    - ansible_distribution               == "RedHat"
    - ansible_distribution_major_version == "7"


# Enable Ansible Repository on RHEL8:
- name: Enable Ansible Repo - RHEL8
  community.general.rhsm_repository:
    name  : ansible-2.9-for-rhel-8-x86_64-rpms
    state : enabled
  when:
    - ansible_distribution               == "RedHat"
    - ansible_distribution_major_version == "8"


...
