---
- name: Check if node_exporter has been previously downloaded and extracted
  stat:
    path: /tmp/node_exporter-1.3.1.linux-amd64/node_exporter
  register: r_node_exporter_check


- name: Download and extract node_exporter to /tmp
  unarchive:
    src        : https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
    dest       : /tmp
    remote_src : yes
  when:
    - not r_node_exporter_check.stat.exists|bool


- name: Add node_exporter user
  user:
    name  : node_exporter
    state : present
    shell : /bin/false


- name: Copy node_exporter binaries into /usr/local/bin
  copy:
    src        : /tmp/node_exporter-1.3.1.linux-amd64/node_exporter
    dest       : /usr/local/bin
    mode       : 0755
    remote_src : yes


- name: Deploy node_exporter unit file
  copy:
    src  : files/node_exporter.service
    dest : /etc/systemd/system/node_exporter.service
    mode : 0644
  notify:
    - reload_systemd


- name: Start and enable node_exporter
  service:
    name    : node_exporter
    state   : started
    enabled : yes


...
